#!/bin/bash

set -ex

invoke build --env-name=root --no-kernel

curl -sL https://aka.ms/InstallAzureCLIDeb | bash

curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"

mv kubectl /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl