#!/bin/bash

set -ex

sudo curl -sL https://aka.ms/InstallAzureCLIDeb | bash

sudo curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"

sudo mv kubectl /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl